[samples]
SAMPLES_DIR = "/Users/jxfer/Library/Application Support/renardo/sample_packs"
MAX_CHANNELS = 2
LOOP_DIR_NAME = "_loop_"
SAMPLES_DOWNLOAD_SERVER = "https://collections.renardo.org/sample_packs"
ALPHA = "abcdefghijklmnopqrstuvwxyz"

[samples.NON_ALPHA]
"&" = "_ampersand"
"*" = "_asterix"
"@" = "_at"
"\\" = "_backslash"
"|" = "_bar"
"^" = "_caret"
":" = "_colon"
"$" = "_dollar"
"=" = "_equals"
"!" = "_exclamation"
"/" = "_forwardslash"
"#" = "_hash"
- = "_hyphen"
"<" = "_lessthan"
"%" = "_percent"
"+" = "_plus"
"?" = "_question"
";" = "_semicolon"
"~" = "_tilde"
"," = "_comma"
0 = "0"
1 = "1"
2 = "2"
3 = "3"
4 = "4"
5 = "5"
6 = "6"
7 = "7"
8 = "8"
9 = "9"

[samples.SYMBOLS_DESCRIPTION]
a = "Gameboy hihat"
A = "Gameboy kick drum"
b = "Noisy beep"
B = "Short saw"
c = "Voice/string"
C = "Choral"
d = "Woodblock"
D = "Dirty snare"
e = "Electronic Cowbell"
E = "Ringing percussion"
f = "Pops"
F = "Trumpet stabs"
g = "Ominous"
G = "Ambient stabs"
h = "Finger snaps"
H = "Clap"
i = "Jungle snare"
I = "Rock snare"
j = "Whines"
J = "Ambient stabs"
k = "Wood shaker"
K = "Percussive hits"
l = "Robot noise"
L = "Noisy percussive hits"
m = "808 toms"
M = "Acoustic toms"
n = "Noise"
N = "Gameboy SFX"
o = "Snare drum"
O = "Heavy snare"
p = "Tabla"
P = "Tabla long"
q = "Ambient stabs"
Q = "Electronic stabs"
r = "Metal"
R = "Metallic"
s = "Shaker"
S = "Tamborine"
t = "Rimshot"
T = "Cowbell"
u = "Soft snare"
U = "Misc. Fx"
v = "Soft kick"
V = "Hard kick"
w = "Dub hits"
W = "Distorted"
x = "Bass drum"
X = "Heavy kick"
y = "Percussive hits"
Y = "High buzz"
z = "Scratch"
Z = "Loud stabs"
- = "Hi hat closed"
"|" = "Hangdrum"
"=" = "Hi hat open"
"/" = "Reverse sounds"
"*" = "Clap"
"\\" = "Lazer"
"~" = "Ride cymbal"
"%" = "Noise bursts"
"^" = "'Donk'"
"$" = "Beatbox"
"#" = "Crash"
"!" = "Yeah!"
"+" = "Clicks"
"&" = "Chime"
"@" = "Gameboy noise"
":" = "Hi-hats"
1 = "Vocals (One)"
2 = "Vocals (Two)"
3 = "Vocals (Three)"
4 = "Vocals (Four)"

[core]
INTERNAL_SETTINGS_FILE = "/Users/jxfer/Library/Application Support/renardo/internal_settings.toml"
RENARDO_ROOT_PATH = "/Users/jxfer/Desktop/renardo/src/renardo"
TUTORIAL_DIR = "/Users/jxfer/Desktop/renardo/src/renardo/lib/demo"
PERFORMANCE_EXCEPTIONS_CATCHING = true

[foxdot_editor]
FOXDOT_EDITOR_ROOT = "/Users/jxfer/Desktop/renardo/src/renardo/foxdot_editor"
ICON = "/Users/jxfer/Desktop/renardo/src/renardo/foxdot_editor/img/icon.ico"
ICON_GIF = "/Users/jxfer/Desktop/renardo/src/renardo/foxdot_editor/img/icon.gif"
THEMES_PATH = "/Users/jxfer/Desktop/renardo/src/renardo/foxdot_editor/themes"

[sc_backend]
SCLANG_CODE_DIR_PATH = "/Users/jxfer/Library/Application Support/renardo/sclang_code"
INFO_FILE = "/Users/jxfer/Library/Application Support/renardo/sclang_code/Info.scd"
RECORD_FILE = "/Users/jxfer/Library/Application Support/renardo/sclang_code/Record.scd"
STARTUP_FILE = "/Users/jxfer/Library/Application Support/renardo/sclang_code/Startup.scd"
OSC_FUNC_FILE = "/Users/jxfer/Library/Application Support/renardo/sclang_code/OSCFunc.scd"
BUFFERS_FILE = "/Users/jxfer/Library/Application Support/renardo/sclang_code/Buffers.scd"
EFFECTS_FILE = "/Users/jxfer/Library/Application Support/renardo/sclang_code/Effects.scd"
SYNTHDEF_DIR = "/Users/jxfer/Library/Application Support/renardo/sclang_code/scsynth"
EFFECTS_DIR = "/Users/jxfer/Library/Application Support/renardo/sclang_code/sceffects"
ENVELOPE_DIR = "/Users/jxfer/Library/Application Support/renardo/sclang_code/scenvelopes"
TMP_SYNTHDEF_DIR = "/Users/jxfer/Library/Application Support/renardo/sclang_code/tmp_code/scsynth"
TMP_EFFECTS_DIR = "/Users/jxfer/Library/Application Support/renardo/sclang_code/tmp_code/sceffects"
SUPERCOLLIDER = ""
